
import { RdsData } from './types';

export const INITIAL_RDS_DATA: RdsData = {
  pi: "----",
  ps: "--------",
  longPs: "",
  rtA: "",
  rtB: "",
  textAbFlag: false,
  rtPlus: [],
  rtPlusItemRunning: false,
  rtPlusItemToggle: false,
  hasRtPlus: false,
  hasEon: false,
  hasTmc: false,
  pty: 0,
  ptyName: "",
  ptyn: "",
  af: [],
  afListHead: null,
  afBLists: {}, 
  afType: 'Unknown',
  tp: false,
  ta: false,
  ms: false, 
  stereo: false, 
  artificialHead: false,
  compressed: false,
  dynamicPty: false,
  ecc: "",
  lic: "",
  pin: "",
  localTime: "",
  utcTime: "",
  eonData: {},
  tmcServiceInfo: { ltn: 0, sid: 0, afi: false, mode: 0, providerName: "[Unavailable]" },
  tmcMessages: [],
  ber: 0,
  rssi: 0,
  snr: 0,
  groupCounts: {},
  groupTotal: 0,
  groupSequence: [],
  recentGroups: [],
  psHistory: [],
  rtHistory: []
};
